#!/usr/bin/env bash
given_year="$*"
[[ "$given_year" =~ [^[:digit:]] && $# == 1 ]] && echo "Usage: leap.sh <year>" && exit 1
[[ $given_year%4 == 0 && $given_year%100 != 0 ]] && echo "true" && exit 0
echo "false"

