#!/usr/bin/env bash
declare -A colors
error (){
    echo "invalid color" && exit 0
}
answer=""
argument_1="$1"
argument_2="$2"
find_key(){
	for key in "${!colors[@]}"; do
		if [[ ${colors[$key]} == $argument_1 || ${colors[$key]} == "$argument_2" ]]; then
			answer+=$key
		fi
done
echo "$answer"
}
colors=([0]=black [1]=brown [2]=red [3]=orange [4]=yellow [5]=green [6]=blue [7]=violet [8]=grey [9]=white)
[[ $# != 2 ]] && error
[[ "${colors[@]}" =~ "$1" && "${colors[@]}" =~ "$2" ]] && find_key && exit 0
error

