#!/usr/bin/env bash
binary=$(echo "obase=2;$1" | bc)
if [[ ${#binary} != 5 ]]; then
	binary=$(echo "$binary" |rev)
	for (( i = 4-${#binary}; i>=0; i--)); do
		binary+=0
	done
	binary=$(echo "$binary" |rev)
fi 
answer=""
declare -A words
words=([4]="wink" [3]="double blink" [2]="close your eyes" [1]="jump")
for (( digit=4; digit >= 0; digit--)); do
    if [[ ${binary:digit:1} == 1 ]]; then
		answer+="${words[$digit]},"
    elif [[ $digit -eq 0 && ${binary:digit:1} == 1 ]]; then
        words=($answer)
        answer=""
        for (( i=${#words[@]}-1; i>=0;i-- )); do 
            echo "$answer"
			echo "$i"
			echo "${words[i]}"
			answer+="${words[i]},"
        done
    fi
done
answer="${answer%?}"
[[ ${answer: -1} == "," ]] && echo "${answer%?}" && exit 0
echo "$answer"
