#!/bin/bash
min=120
max=130
i=0
while true
do
if [[ i -eq 10 ]]; then
	for ((j=5; j>=0; j--)); do
		echo $'\a'
		sleep 1
	done
	i=0
fi
time=$(shuf -i $min-$max -n 1)
sleep $time
echo $'\a'
sleep 11
echo $'\a'
i+=1
done
